### ISSUE TITLE
 Add an Array Variant to Content Enum

### ISSUE THREAD

**Issue by imotai** [dongri/openai-api-rs#102]
### Describe the feature or improvement you're requesting

I would like to propose adding an Array variant to the Content enum in the library. This addition would allow users to support JSON content more effectively, enabling the handling of arrays directly within the enum.

### Additional context

Currently, the Content enum does not support array structures, which limits the flexibility when working with JSON data. By adding this variant, it would align with common use cases in API interactions where JSON arrays are prevalent.

**Comment by dongri** [comment]
@imotai Specifically, what API are you referring to?
