### ISSUE TITLE
Bring back support for sync requests

### ISSUE THREAD

**Issue by sztomi** [dongri/openai-api-rs#103]
### Describe the feature or improvement you're requesting

#92 says it introduces support for async, but it also seems to fully remove sync requests. This is a disruptive and likely undersirable change for applications that are not already async. Is there any chance to bring back support for sync operations?

**Comment by dongri** [comment]
I wanted to continue processing synchronously, but I changed to asynchronous because the library I was using had various flaws.

What specific inconveniences are there?

**Comment by dongri** [comment]
@sztomi I see, understanding the challenge of depending on tokio can indeed make the program larger. However, you're struggling to find a good way to support both synchronous and asynchronous execution. Do you have any good ideas?

**Comment by dongri** [comment]
We will proceed with a policy of not responding to this. Sorry!!!!!!!!!!!!!!!
