### ISSUE TITLE
Batch API unsupported

### ISSUE THREAD

**Issue by fmhall** [dongri/openai-api-rs#106]
### Describe the feature or improvement you're requesting

OpenAI now has a Batch API, which is not currently supported by this crate.

https://platform.openai.com/docs/api-reference/batch

**Comment by dongri** [comment]
@fmhall https://github.com/dongri/openai-api-rs/pull/107
I have added the batch API. Please use v5.0.6.  
You can find a sample here https://github.com/dongri/openai-api-rs/blob/main/examples/batch.rs

**Comment by fmhall** [comment]
Thank you!

**Comment by fmhall** [comment]
You might also want to add it to the list of supported APIs in the README :)
