### ISSUE TITLE
Support for OpenAI realtime API

### ISSUE THREAD

**Issue by Boscop** [dongri/openai-api-rs#114]
I'm curious if you are planning to add support for the OpenAI realtime API?
That would also be very useful :)

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/115/files

**Comment by Boscop** [comment]
Wow, thanks so much!

**Comment by Boscop** [comment]
@dongri Does the realtime API client also work on WASM and supports tool use? :)
