### ISSUE TITLE
invalid type: map, expected a string

### ISSUE THREAD

**Issue by Wandalen** [dongri/openai-api-rs#116]
### Describe the bug

List of assistants does not work.
Looks like serde error?
How can I see more verbose output?

```
Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid type: map, expected a string", line: 90, column: 25) })
```

### To Reproduce

```rust
let response = client.list_assistant( None, None, None, None ).await?;
```

### Code snippets

```JavaScript
let response = client.list_assistant( None, None, None, None ).await?;
```

### OS

windows

### Rust version

1.83

### Library version

5.0.11

**Comment by dongri** [comment]
Are you using rust version 1.83?

https://github.com/rust-lang/rust/blob/master/RELEASES.md
Latest version is 1.81

Rust version: 1.81
Library version: 5.011

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = OpenAIClient::new(env::var("OPENAI_API_KEY").unwrap().to_string());

    let response = client.list_assistant(None,None,None,None).await?;
    println!("List Assistants: {:?}", response);

    return Ok(());
}
```
The output was correct.
```
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 5.14s                                                                                                                                              
     Running `target/debug/examples/assistant`                                                                                                                                                                       
List Assistants: ListAssistant { object: "list", data: [AssistantObject { id: "asst_ryF3DSKvHzNzcJ1VYTWGmVtP", object: "assistant", created_at: 1721519486, name: None, description: Some("this is a test assistant")
, model: "gpt-4o", instructions: Some("You are a personal math tutor. When asked a question, write and run Python code to answer the question."), tools: [{"type": "code_interpreter"}], tool_resources: Some(ToolRes
ource { code_interpreter: Some(CodeInterpreter { file_ids: Some([]) }), file_search: None }), metadata: Some({}), headers: None }, AssistantObject { id: "asst_HO75Y4iznskvHWk6VBkesYag", object: "assistant", create
d_at: 1721519310, name: None, description: Some("this is a test assistant"), model: "gpt-4o", instructions: Some("You are a personal math tutor. When asked a question, write and run Python code to answer the quest
ion. please json format"), tools: [{"type": "code_interpreter"}], tool_resources: Some(ToolResource { code_interpreter: Some(CodeInterpreter { file_ids: Some([]) }), file_search: None }), metadata: Some({}), heade
rs: None }, AssistantObject { id: "asst_VSz98VLPbxeRWx8wr51hQGeD", object: "assistant", created_at: 1721519020, name: None, description: Some("this is a test assistant"), model: "gpt-4o", instructions: Some("You a
.......
```

```

**Comment by Wandalen** [comment]
Hi Jin! How are you doing? Thanks for this open-source project.

I'm encountering an issue with the code, which results in the following error:

```
Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid type: map, expected a string", line: 90, column: 25) })
```

I'm using the nightly version, and the stable 1.81 version gives the same results.

My best guess is that the response from OpenAI contains something that `serde` can't parse, and the error report doesn't clearly indicate what is different in the response I'm receiving from OpenAI. I tried using `curl`, and the response looks fine, but it seems that `openai-api-rs` fails to parse it.

Another possibility is the size of the response. Perhaps I have too many assistants, and the way the response is handled doesn't account for something.

I suggest improving the quality of the error message by including a slice of the response that caused the error, so it's clear how to fix the bug. For example, [miette](https://docs.rs/miette/latest/miette/) does a great job formatting slices of text.

<img width="610" alt="serde_json" src="https://github.com/user-attachments/assets/e5226a0e-bb2f-43c3-af4b-fd1a4389b100">

**Comment by dongri** [comment]
@Wandalen 
Fixed error response
https://github.com/dongri/openai-api-rs/pull/117/files

Please try use v5.0.12

**Comment by Wandalen** [comment]
Thank you for the quick response, Jin.

Unfortunately, the change prints the entire response, so it's unclear exactly which line serde failed to parse. I’ve removed sensitive information and published the first 30 lines, though I’m not sure if the data I’ve provided is detailed enough to be helpful.

```json
Error: CustomError { message: "Failed to parse JSON: invalid type: map, expected a string at line 90 column 25 / response {
  \"object\": \"list\",
  \"data\": [
    {
      \"id\": \"...\",
      \"object\": \"assistant\",
      \"created_at\": 1728325306,
      \"name\": \"Image Describe\",
      \"description\": null,
      \"model\": \"gpt-4o-2024-08-06\",
      \"instructions\": \"# Image Describe\
\
You are ...
\
### Attributes\
\
Begin your description by listing all applicable attributes from the following categories:\
\
<attribute_categories>\
Scene Setting/Environment\
Perspective/Angle\
Lighting\
Time of Day/Season\
Color Palette\
Textures\
Objects/Elements\
Characters/Subjects\
Action/Motion\
Style/Artistic Approach\
Mood/Atmosphere\
Background Details\
Foreground Details\
Depth of Field/Focus\
Proportions and Scale\
...
```

By the way, the list of files works perfectly fine.

**Comment by dongri** [comment]
Ok, send me the response dump at dongrium@gmail.com and I'll look into it. (Please edit confidential information)

**Comment by dongri** [comment]
Ok, send me the response dump at dongrium@gmail.com and I'll look into it. (Please edit confidential information)

**Comment by Wandalen** [comment]
I've just sent it. I hope that helps. 

Programmatically selecting lines would address other similar issues.

**Comment by dongri** [comment]
@Wandalen 
Thank you sent me log
I fixed the response in the tools section a bit, mainly around functions.
Could you please try again with v5.0.13?

**Comment by dongri** [comment]
Changed code: https://github.com/dongri/openai-api-rs/pull/118/files
