### ISSUE TITLE
Support API parameters

### ISSUE THREAD

**Issue by cryingpotat0** [dongri/openai-api-rs#12]
### Describe the feature or improvement you're requesting

Thanks for making this package! I think having support for other API parameters (https://platform.openai.com/docs/api-reference/completions) like temperature/ n_tokens will be super helpful.

Also any reason the model names are consts vs some enum structure?

**Comment by dongri** [comment]
@cryingpotat0 
https://github.com/dongri/openai-api-rs/pull/13

Add parameters for chat completions

**Comment by dongri** [comment]
@cryingpotat0 can use v0.1.9

**Comment by cryingpotat0** [comment]
Thanks so much!
