### ISSUE TITLE
Generate embedding for an array of strings

### ISSUE THREAD

**Issue by josmontes** [dongri/openai-api-rs#120]
### Describe the feature or improvement you're requesting

I noticed that in the embedding request the input field is only a string while openai supports an array of strings to generate multiple embeddings in one single request.

If we could change the input type to Vec<String> itd be amazing.

```
impl EmbeddingRequest {
    pub fn new(model: String, input: Vec<String>, dimensions: Option<i32>) -> Self {
        Self {
            model,
            input,
            dimensions,
            user: None,
        }
    }
}
```

### Additional context

Love your work man, thanks for this!
Note: I also added dimensions as an option since its suggested to include it in [OpenAI's official guides](https://platform.openai.com/docs/guides/embeddings#use-cases):
> In general, using the dimensions parameter when creating the embedding is the suggested approach.

**Comment by josmontes** [comment]
Let me know if you'd like me to open a PR and ill for sure lend a hand!

**Comment by dongri** [comment]
@josmontes Thanks!
I have revised the code.
https://github.com/dongri/openai-api-rs/pull/121

Can you use v5.0.15

**Comment by dongri** [comment]
The dimensions parameter can be set as follows.
https://github.com/dongri/openai-api-rs/blob/v5.0.15/examples/embedding.rs#L14
