### ISSUE TITLE
Library doesn't support setting custom headers

### ISSUE THREAD

**Issue by funCapital** [dongri/openai-api-rs#122]
### Description
Some integrations with LLM providers require setting custom headers in API requests. For example, I am using [Helicone](https://helicone.ai/) alongside [PostHog](https://posthog.com/), which requires additional headers (`Helicone-Auth`, `Helicone-Posthog-Key`, etc.) to track usage and analytics effectively. However, I could not find an option to set custom headers in the OpenAI library.

### Expected Behavior
The client initialization could allow a default_headers parameter to define headers that apply to all requests, e.g.:

```py
client = OpenAI(
    api_key="<your-api-key>",
    default_headers={
        "Helicone-Auth": f"Bearer {HELICONE_API_KEY}",
        "Helicone-Posthog-Key": "<ph_project_api_key>",
        "Helicone-Posthog-Host": "<ph_client_api_host>",  # Optional
    }
)
```
This would provide flexibility for monitoring, analytics, and other third-party integrations.

### Proposed Implementation
If this feature is not currently supported, I am happy to contribute by submitting a PR to add this functionality. Please let me know if this aligns with the library's goals.

### Use Cases

Tracking requests with Helicone and PostHog.
Supporting other custom integrations that require headers.
### Steps Taken
I reviewed the library documentation and source code but could not find support for setting default headers. If this feature is already available, I'd appreciate guidance on how to use it.

**Comment by dongri** [comment]
Got it; I understand what you're aiming to do. Let me think about how to implement it. I’d like to tidy up `new_with_xxxx`.

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/123/files
I responded in this way.

@funCapital Please use v5.2.0.

```
let api_key = env::var("OPENAI_API_KEY").unwrap().to_string();
let client = OpenAIClient::builder()
    .with_api_key(api_key)
    .with_endpoint("https://oai.helicone.ai/v1")
    .with_header("Helicone-Auth", "sk-helicone-xxxxxx")
    .with_header("Helicone-Posthog-Key", "<ph_project_api_key>")
    .build()?;
```
I think we can use the Helicone API if we write it this way.
