### ISSUE TITLE
Assistant API: Assistant with File Search throws parsing error

### ISSUE THREAD

**Issue by niklasHack2810** [dongri/openai-api-rs#125]
### Describe the bug

Creating a run with an assistant with file search throws an error:

Error: OpenAI: APIError: Failed to parse JSON: invalid type: map, expected a string at line 20 column 21 / response

This happens in the tools property. The actual content of the property is the following:
```json
  "tools": [
    {
      "type": "file_search",
      "file_search": {
        "ranking_options": {
          "ranker": "default_2024_08_21",
          "score_threshold": 0.0
        }
      }
    }
  ],
```

In the library, it is defined as 
```rust
pub tools: Vec<HashMap<String, String>>,
```

### To Reproduce

1. Create an assistant with a file search
2. Execute create_run()

### OS

Linux

### Rust version

1.82.0

### Library version

5.2.1

**Comment by dongri** [comment]
@niklasHack2810 Could you paste the snippet of code you executed?
Like  https://github.com/dongri/openai-api-rs/blob/main/examples/assistant.rs#L12-L24

**Comment by niklasHack2810** [comment]
@dongri This line fails:

```rust
let run = self.client.create_run(thread_id.clone(), CreateRunRequest::new(ASSISTANT_ID.to_string())).await?;
```

self.client is your OpenAIClient, thread_id is from a previous request to client.create_thread. The ASSISTANT_ID is just a constant &str.

**Comment by dongri** [comment]
Fixed
Please use v5.2.2

**Comment by niklasHack2810** [comment]
Thank you, it works now :)
