### ISSUE TITLE
Annotations in create_run cause Parse Error

### ISSUE THREAD

**Issue by niklasHack2810** [dongri/openai-api-rs#127]
### Describe the bug

When retrieving the messages of a run, the request sometimes returns a parse error, because the field annotations in the struct ContentText is only defined as a Vec<String>, but its actually a different structure like below:

```json
            "annotations": [
              {
                "type": "file_citation",
                "text": "【4:0†source】",
                "start_index": 554,
                "end_index": 566,
                "file_citation": {
                  "file_id": "file-yvzTtVlX0wZTHEh66xdtGIcO"
                }
              }
            ]
```

This seems to happen with assistants with uploaded files and if you ask a question relating to the file.

### To Reproduce

1. Create a run
2. After the run, query the list of messages

### Code snippets

```JavaScript
self.client.list_messages(thread_id.clone()).await
```

### OS

Linux

### Rust version

1.82.0

### Library version

5.2.2

**Comment by dongri** [comment]
@niklasHack2810 Fixed
https://github.com/dongri/openai-api-rs/pull/128

Please use v5.2.3

**Comment by niklasHack2810** [comment]
Thank you, works now :+1:
