### ISSUE TITLE
Error types are not Send & Sync

### ISSUE THREAD

**Issue by pragmatrix** [dongri/openai-api-rs#129]
Hi, 

I'd like to use the realtime API and the first roadblock is that the error types are not Send + Sync, which breaks compatibility with anyhow. I'll wrap the errors for now, but thought you should know. Tell me if you'd like me to provide a PR or if you plan to introduce custom errors anyway.

**Comment by dongri** [comment]
@pragmatrix Thank you!
Please give me a pull request. Thanks!
