### ISSUE TITLE
Feature request: function variant in MessageRole enum

### ISSUE THREAD

**Issue by Anush008** [dongri/openai-api-rs#14]
### Describe the feature or improvement you're requesting

Hey. Thanks for the great library. Have used it quite a lot. I've been trying to work out a feature using function calls. But I noticed that the `MessageRole` enum doesn't have the `function` variant. https://github.com/dongri/openai-api-rs/blob/4521588b8097628db2dd58d479b5035b9aee1611/src/v1/chat_completion.rs#L46-L52
As mentioned in the OpenAI reference here.
https://platform.openai.com/docs/api-reference/chat/create#chat/create-role

**Comment by dongri** [comment]
Add function in role and add example
https://github.com/dongri/openai-api-rs/pull/15/files

**Comment by dongri** [comment]
@Anush008 You can use v0.1.10

**Comment by Anush008** [comment]
Great. Thank you for the prompt response @dongri.
