### ISSUE TITLE
Allow to override https://api.openai.com/v1

### ISSUE THREAD

**Issue by ianpurton** [dongri/openai-api-rs#18]
### Describe the feature or improvement you're requesting

I'd like to use `openai-api-rs` with [Local AI](https://github.com/go-skynet/LocalAI)

To do that I'll need the ability to specify for example https://localhost:8080/v1 as the API endpoint.

Something like

```rust

impl Client {
    ...
    pub fn new_with_endpoint(api_url: String) -> Self {
        Self { 
            api_key: None,
            api_url: Some(api_url) 
        }
    }
    ...
}
```

### Additional context

I'm seeing a few projects now re-implementing the Open AI API spec as a way to plug in different LLM's.

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/19/files
Add `new_with_endpoint`
You can use `v0.1.12`
