### ISSUE TITLE
Making api_base a environment variable at runtime.

### ISSUE THREAD

**Issue by michaelfeil** [dongri/openai-api-rs#21]
### Describe the feature or improvement you're requesting

https://github.com/dongri/openai-api-rs/blob/e34bde5e78a6228e00bfbf24af81a3125880a23e/src/v1/api.rs#L29C1-L30C1

Reading from os env variables, with defaulting to ` &str = "https://api.openai.com/v1";`

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/22/files

**Comment by dongri** [comment]
@michaelfeil 
https://github.com/dongri/openai-api-rs/pull/22/files
Add default endpoint
