### ISSUE TITLE
Re-use reqwest::Client instead of constructing one per request

### ISSUE THREAD

**Issue by Boscop** [dongri/openai-api-rs#26]
`Client::post` creates a new reqwest::Client on each request.

Reasoning from the reqwest docs on why you should re-use a client instead of building a new one:

> The Client holds a connection pool internally, so it is advised that you create one and reuse it.

> You do not have to wrap the Client in an [Rc](https://doc.rust-lang.org/nightly/alloc/rc/struct.Rc.html) or [Arc](https://doc.rust-lang.org/nightly/alloc/sync/struct.Arc.html) to reuse it, because it already uses an [Arc](https://doc.rust-lang.org/nightly/alloc/sync/struct.Arc.html) internally.

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/31
I changed from reqwest to minreq in this PR.
