### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by Boscop** [dongri/openai-api-rs#30]
Currently the crate always depends on tokio which means it can't be compiled to wasm for use in frontends that want to make OpenAI API requests.
It would be great to make the tokio dependency optional to allow compiling to wasm.
(`reqwest` will work when compiling to wasm.)

**Comment by dongri** [comment]
@Boscop 
Now the latest main branch has removed dependencies on reqwest and tokio. Can I do Wasm support with this?
