### ISSUE TITLE
Missing struct option on ChatCompletionRequest function_call type

### ISSUE THREAD

**Issue by the-spice-must-flow** [dongri/openai-api-rs#33]
### Describe the bug

[From openai docs](https://platform.openai.com/docs/guides/gpt/function-calling)
If you want to force the model to call a specific function you can do so by setting function_call: {"name": "insert-function-name"}. You can also force the model to generate a user-facing message by setting function_call: "none". Note that the default behavior (function_call: "auto") is for the model to decide on its own whether to call a function and if so which function to call.

The current implementation only supports strings like "auto" or "none"

But the type should be an enum of auto, none and a struct that becomes {"name": "function-name"}

### To Reproduce

1. Create a new ChatCompletionRequest instance.
2. add an api-valid function_call shape like a struct that deserialises { "name": "function-name" }
3. Code will not compile because function_call only accepts Option<String>

### Code snippets

```JavaScript
pub struct ChatCompletionRequest {
    // ... 
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<String>, // can this be an enum of "auto" or { "name": "function-name" } instead 
}
```

### OS

macOS

### Rust version

1.72.0

### Library version

openai-api-rs v1.0.1

**Comment by dongri** [comment]
@the-spice-must-flow Thank you for report the bug
https://github.com/dongri/openai-api-rs/pull/34

**Comment by the-spice-must-flow** [comment]
Thanks so much for the quick change. Just for completion though,

"none" is another valid type. It forces openai to not make a function call. I'm not sure if this different from None. But just to accurately match the docs, it might be worth adding that type as well.

From docs
| You can also force the model to generate a user-facing message by setting function_call: "none".

**Comment by dongri** [comment]
OK, "none" will be added

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/35/files
DONE

**Comment by dongri** [comment]
v1.0.3

**Comment by the-spice-must-flow** [comment]
Sorry to report that the fix doesn't serialise correctly.

if you do the following:

```rust
ChatCompletionRequest {
...
function_call: FunctionCallType::function { name: "some_function".to_string() },
...
}
```

You will get the following JSON which is an invalid openai API request

```json
{
// ...
"function_call":{"function":{"name":"some_function"}}
}
```

But a valid request is just:

```json
{
// ...
"function_call": { "name":"some_function" }
}
```

**Comment by dongri** [comment]
Fixed
```
    Finished dev [unoptimized + debuginfo] target(s) in 1.60s                                                                                                                                                         
     Running `target/debug/examples/function_call`                                                                                                                                                                    
{"model":"gpt-3.5-turbo-0613","messages":[{"role":"user","content":"What is the price of Ethereum?"}],"functions":[{"name":"get_coin_price","description":"Get the price of a cryptocurrency","parameters":{"type":"ob
ject","properties":{"coin":{"type":"string","description":"The cryptocurrency to get the price of"}},"required":["coin"]}}],"function_call":{"name":"test"}} 
```
Please use v1.0.4
