### ISSUE TITLE
Deprecated `functions` field of chat completion API.

### ISSUE THREAD

**Issue by krinistof** [dongri/openai-api-rs#47]
Hey!
First of all, thank you for the maintenance of the library! The following docs was recently updated, and the given field of the struct is now deprecated. I would like to Open a PR of refactor in the future. Wdyt?

docs: https://platform.openai.com/docs/api-reference/chat/create#chat-create-functions
field: https://github.com/dongri/openai-api-rs/blob/62f948e8ff2e530440cd918597afc5dcc81f9212/src/v1/chat_completion.rs#L21C1-L21C1

**Comment by dongri** [comment]
@krinistof Thank you. Please PR
