### ISSUE TITLE
TTS and Whisper example?

### ISSUE THREAD

**Issue by overheat** [dongri/openai-api-rs#52]
### Describe the feature or improvement you're requesting

https://platform.openai.com/docs/models/tts
https://platform.openai.com/docs/models/whisper

more examples, please.

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/blob/add-tts-samples/examples/text_to_speech.rs
Additional TTS samples.

Whisper samples cannot be uploaded in `multipart/form-data` and will be added in the future.

Ref: https://github.com/dongri/openai-api-rs/issues/51
