### ISSUE TITLE
Correctly version breaking changes

### ISSUE THREAD

**Issue by jpmcb** [dongri/openai-api-rs#58]
### Describe the bug

There have been a few breaking changes that have not been labeled as breaking: i.e., the major version of the cargo package is not being incremented to indicate breaking changes.

Specifically, it looks like https://github.com/dongri/openai-api-rs/pull/46 should have been a breaking change since it mutated the chat response types to be an `Option`

Without consistent and predicable versioning, it makes using this library brittle during upgrades.

A few suggestions:
- Declare a `VERSIONING.md` and document what consumers can expect from versions of this package
- Stick to semver semantics (and mark breaking changes as major version releases)

### To Reproduce

1. Use version 2.0.2
2. Attempt to upgrade to the latest 2.1.7
3. Notice the following build errors using chat response types:

```
error[E0308]: mismatched types
   --> src/conversation/mod.rs:102:25
    |
101 |                     match response.choices[0].finish_reason {
    |                           --------------------------------- this expression has type `std::option::Option<FinishReason>`
102 |                         FinishReason::function_call => {
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Option<FinishReason>`, found `FinishReason`
    |
    = note: expected enum `std::option::Option<FinishReason>`
               found enum `FinishReason`
```

I would not expect type changes from a minor version bump.

### OS

Linux

### Rust version

1.75

### Library version

2.0.2

**Comment by dongri** [comment]
@jpmcb Thank you for the report
Sorry, not strictly checking for version compatibility issues.
Please using latest version v3.0.0
