### ISSUE TITLE
How to do GPT3?

### ISSUE THREAD

**Issue by nikitavoloboev** [dongri/openai-api-rs#6]
### Describe the feature or improvement you're requesting

Tried this, I guess no support yet?

<img width="428" alt="image" src="https://user-images.githubusercontent.com/6391776/235372308-1ca34922-4fcd-4ec6-a9b4-c06bf9d7d110.png">

Would really love to use GPT3, thanks ♥️

**Comment by dongri** [comment]
You can use following consts
https://github.com/dongri/openai-api-rs/blob/main/src/v1/chat_completion.rs#L5-L10
```
model: chat_completion::GPT3_5_TURBO.to_string()
or
model: chat_completion::GPT3_5_TURBO_0301.to_string()
```

**Comment by nikitavoloboev** [comment]
Perfect, thank you
