### ISSUE TITLE
Field marked as deprecated causes pipeline failure even though value used is `None`

### ISSUE THREAD

**Issue by OnlyFerris** [dongri/openai-api-rs#61]
### Describe the bug

```text
error: use of deprecated field `v1::chat_completion::ChatCompletionRequest::function_call`: This field is deprecated. Use `tool_choice` instead.
  --> src/v1/chat_completion.rs:77:13
   |
77 |             function_call: None,
   |             ^^^^^^^^^^^^^^^^^^^
```

It seems that marking the field as deprecated is not working as intended. Even though "None" is specified, it triggers a complaint, which makes pipeline fail. In the code where the `ChatCompletionRequest` constructs itself using its `new(...)` method.

This change was introduced in https://github.com/dongri/openai-api-rs/pull/54

### To Reproduce

See pipeline in main branch

### OS

All

### Rust version

Any

### Library version

openai-api-rs v2.1.7

**Comment by dongri** [comment]
@OnlyFerris Thank you!
I remove Deprecated function
https://github.com/dongri/openai-api-rs/pull/63
