### ISSUE TITLE
Run CI pipeline on PRs always, before merging

### ISSUE THREAD

**Issue by OnlyFerris** [dongri/openai-api-rs#62]
### Describe the feature or improvement you're requesting

To avoid CI breaking changes getting into main, such as https://github.com/dongri/openai-api-rs/issues/61 which was caused by https://github.com/dongri/openai-api-rs/pull/54, the CI pipeline should run on PRs before they can be merged

### Additional context

Make it so that this is enforced by GitHub.

**Comment by dongri** [comment]
Checked for CI
@OnlyFerris Thank you!
