### ISSUE TITLE
Updated GPT-4 Turbo preview

### ISSUE THREAD

**Issue by o-agassizii** [dongri/openai-api-rs#68]
### Describe the feature or improvement you're requesting

> Today, we are releasing an updated GPT-4 Turbo preview model, `gpt-4-0125-preview`. [...] we are also introducing a new `gpt-4-turbo-preview` model name alias, which will always point to our latest GPT-4 Turbo preview model

https://openai.com/blog/new-embedding-models-and-api-updates

### Additional context

Make these available in the crate please :)

**Comment by dongri** [comment]
@o-agassizii Added new models, please use v4.0.3

**Comment by o-agassizii** [comment]
tysm @dongri 💜
