### ISSUE TITLE
Derive deserialize for ChatCompletionResponse

### ISSUE THREAD

**Issue by o-agassizii** [dongri/openai-api-rs#69]
### Describe the feature or improvement you're requesting

In 4.0.1 the definition of `ChatCompletionResponse` is:

```rust
#[derive(Debug, Deserialize)]
pub struct ChatCompletionResponse {
    pub id: String,
    pub object: String,
    pub created: i64,
    pub model: String,
    pub choices: Vec<ChatCompletionChoice>,
    pub usage: common::Usage,
    pub system_fingerprint: Option<String>,
}
```

I would like that in addition to `Debug` and `Deserialize`, it would also derive `Serialize`.

### Additional context

This is desirable because deriving Serialize would allow structured logging to serialize to JSON for logging and tracing purposes.

**Comment by dongri** [comment]
@o-agassizii Added Serialize, please use v4.0.3

**Comment by o-agassizii** [comment]
Thank you very much @dongri
