### ISSUE TITLE
Embedding response error

### ISSUE THREAD

**Issue by LukeThayer** [dongri/openai-api-rs#7]
### Describe the bug

the program returns the following error: 
Error: APIError { message: "error decoding response body: missing field `usage` at line 1545 column 5" }

not sure if this is due to change in the API

### To Reproduce

first create an instance of a client with your API,
generate a embedding request,
send a embedding request

### Code snippets

```JavaScript
`let req = EmbeddingRequest {
model: "text-embedding-ada-002".to_string(),
input: "story time".to_string(),
user: Option::None,
}

let result = client.embedding(req).await?;
println!("{:?}, result");

Ok(())
`
```

### OS

macOS

### Rust version

Rust v1.64.0

### Library version

v0.1.0

**Comment by dongri** [comment]
@LukeThayer Thanks for reporting the bug!

Fixed response to Embedding.
https://github.com/dongri/openai-api-rs/pull/8/files

I got confirmation with this sample code.
https://github.com/dongri/openai-api-rs/blob/v0.1.7/examples/embedding.rs

You can use v0.1.7
