### ISSUE TITLE
Derive serialize for EmbeddingResponse

### ISSUE THREAD

**Issue by o-agassizii** [dongri/openai-api-rs#71]
### Describe the feature or improvement you're requesting

Hi. Thank you for adding derive serialize for `ChatCompletionResponse`.

I would also like to ask for this to be done for `EmbeddingResponse` as well :)

```rust
#[derive(Debug, Deserialize)]
pub struct EmbeddingResponse {
    pub object: String,
    pub data: Vec<EmbeddingData>,
    pub model: String,
    pub usage: Usage,
}
```

I would like that in addition to `Debug` and `Deserialize`, this one would also derive `Serialize` as well.

### Additional context

Same motivation as in issue #69 (nice), but for `EmbeddingResponse`

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/72/files
Added serialize
@o-agassizii please use v4.0.4

**Comment by o-agassizii** [comment]
Thank you @dongri 😊
