### ISSUE TITLE
Eq and PartialEq Traits 

### ISSUE THREAD

**Issue by ryanolson** [dongri/openai-api-rs#75]
### Describe the feature or improvement you're requesting

Many of the API structs should have `Eq, PartialEq` traits

example:

```
#[derive(Debug, Deserialize, Serialize, Clone, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub enum MessageRole {
    user,
    system,
    assistant,
    function,
}
```

**Comment by dongri** [comment]
https://github.com/dongri/openai-api-rs/pull/76
@ryanolson Added
