### ISSUE TITLE
All objects should Serialize and Deserialize

### ISSUE THREAD

**Issue by ryanolson** [dongri/openai-api-rs#77]
### Describe the feature or improvement you're requesting

All object in the API should support Serialization and Deserialization.

### Additional context

Example:

`openai_api_rs::v1::chat_completion::ChatCompletionRequest` support Serialization, but not Deserialization.

One of my goals with this project is to implement mock services which requires my service handlers to deserialize `ChatCompletionRequest` object and issue some dummy responses.

The current design does not allow for this.

@dongri - big thanks for the quick turn around on the other issue.

**Comment by dongri** [comment]
@ryanolson https://github.com/dongri/openai-api-rs/pull/78 merged
