### ISSUE TITLE
Return rate limit information for each completed request

### ISSUE THREAD

**Issue by daniel-abramov** [dongri/openai-api-rs#80]
### Describe the feature or improvement you're requesting

OpenAI API returns [rate limits in headers](https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers).  This is useful for implementing production apps that must respect the rate limits and introduce strategies like exponential backoff or similar to deal with the limits.

An alternative strategy would be to provide one of the rate limit handling back-off strategies built into the library with the possibility to configure one. That being said, since different apps may want to have different behaviors, returning this information to the user is still crucial to allowing developers to implement the desired behavior.

**Comment by dongri** [comment]
@daniel-abramov Thank you for the feedback
https://github.com/dongri/openai-api-rs/pull/81
made it possible to return headers in the response. You can check the rate limit information within them
Please use v4.0.8
https://github.com/dongri/openai-api-rs/blob/main/examples/chat_completion.rs#L20

**Comment by daniel-abramov** [comment]
Awesome, thanks!
