### ISSUE TITLE
Support api-key header

### ISSUE THREAD

**Issue by khaneliman** [dongri/openai-api-rs#82]
### Describe the feature or improvement you're requesting

I'm working with an azure openai endpoint that doesn't accept authentication through a Bearer token. I need to pass in an api-key header. I dont know if there's any harm in sending an additional header with the api-key or it should be a different signature.

**Comment by dongri** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Cpython-new&pivots=rest-api#rest-api

I saw this document, but it's not 100% compatible with the official OpenAI API, so I think it's better to look for another crate. This library is a library dedicated to OpenAI.
