### ISSUE TITLE
Timeout support

### ISSUE THREAD

**Issue by brynary** [dongri/openai-api-rs#89]
### Describe the feature or improvement you're requesting

Support to specify a request timeout using minireq timeout support

https://docs.rs/minreq/latest/minreq/#timeouts

### Additional context

I could likely implement this feature if a patch would be accepted.

**Comment by dongri** [comment]
@brynary 
https://github.com/dongri/openai-api-rs/pull/90
Supported HTTP timeout.

**Comment by brynary** [comment]
Thank you, and thanks for this project!
