### ISSUE TITLE
What for a String do i need for AudioTranscriptionRequest?

### ISSUE THREAD

**Issue by NewtTheWolf** [dongri/openai-api-rs#91]
I tried to use a File Path where the file is located, i also tried to use a File Buf

i always getting the error:
```
APIError { message: "400: {\n  \"error\": {\n    \"message\": \"1 validation error for Request\\nbody -> file\\n  field required (type=value_error.missing)\",\n    \"type\": \"invalid_request_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}" }
```

my code:
```rust
let transcript = AudioTranscriptionRequest::new("E:\\Downloads\\demo.mp3".to_string(), WHISPER_1.to_owned());
let transcript_response = client.audio_transcription(transcript).unwrap();
```

`println!("Transcript: {:?}", transcript);`
```
Transcript: AudioTranscriptionRequest { file: "E:\\Downloads\\demo.mp3", model: "whisper-1", prompt: None, response_format: None, temperature: None, language: None }
```

**Comment by DanteVillarreal** [comment]
I have the same issue. Can we have an example for Transcription?

**Comment by dongri** [comment]
@NewtTheWolf @DanteVillarreal 
Thank you very much for your patience. I have fixed the HTTP client, and it is now working correctly.
I created a sample like this: 
https://github.com/dongri/openai-api-rs/blob/main/examples/audio_transcriptions.rs. 
Please refer to it and Please use v5.0.0
